# Generated by Django 5.0.6 on 2024-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Contact', models.CharField(max_length=50)),
            ],
        ),
    ]
