# Generated by Django 5.0.6 on 2024-07-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='emp',
        ),
    ]
