# Generated by Django 5.0.6 on 2024-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudeApp', '0002_alter_emp_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='FullName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
