# Generated by Django 5.0.1 on 2024-07-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudeApp', '0003_emp_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'empimg',
            },
        ),
    ]
