# Generated by Django 5.0.1 on 2024-07-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudeApp', '0004_empimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empimg',
            new_name='IMG',
        ),
    ]
