# Generated by Django 5.1 on 2024-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudeApp', '0005_rename_empimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
